
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [4]:
import numpy as np
array_1d=np.array([])
for i in range(10):
    array_1d = np.append(array_1d, i)
array_1d

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [10]:
array_1_1d=np.array([0,1,2,3,4,5,6,7,8])
array_2_3d=np.reshape(array_1_1d,(3,3))
array_2_3d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Access the element at the second row, second column.


In [11]:
array_2_3d[1,1]

4

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [17]:
list_1=[1, 2, 3]
list_2=[4, 5, 6]
array_add=np.array(list_1)+np.array(list_2)
array_sub=np.array(list_1)-np.array(list_2)
array_multi=np.array(list_1)*np.array(list_2)
array_divide=np.array(list_1)/np.array(list_2)
print(f"ADDITION={array_add}\nSUBTRACTION={array_sub}\nMULTIPLICATION={array_multi}\nDIVISION={array_divide}")

ADDITION=[5 7 9]
SUBTRACTION=[-3 -3 -3]
MULTIPLICATION=[ 4 10 18]
DIVISION=[0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [20]:
list_3=np.array([[1, 2, 3, 4, 5]])
sum=np.sum(list_3)
mean=np.mean(list_3)
standard=np.std(list_3)
print(f"SUM={sum}\nMEAN={mean}\nSTANDARD DEVIATION={standard}")

SUM=15
MEAN=3.0
STANDARD DEVIATION=1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [21]:
np.reshape( [1, 2, 3, 4, 5, 6],(2,3))

array([[1, 2, 3],
       [4, 5, 6]])


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [22]:
random_array = np.random.randint(0, 10, size=(5, 5))
random_array

array([[9, 0, 9, 4, 6],
       [1, 0, 0, 7, 2],
       [6, 9, 2, 6, 7],
       [8, 0, 0, 8, 1],
       [4, 1, 6, 9, 7]])

Replace all values in the sub-array with a specific value.


In [24]:
random_array[2,[0,1,2,3,4]]=804
random_array

array([[  9,   0,   9,   4,   6],
       [  1,   0,   0,   7,   2],
       [804, 804, 804, 804, 804],
       [  8,   0,   0,   8,   1],
       [  4,   1,   6,   9,   7]])

Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [41]:
list_4=[[1, 2], [3, 4], [5, 6], [7, 8]]
array_3_4x2d=np.array(list_4)
array_3_4x2d[[1,3]]

array([[3, 4],
       [7, 8]])

#### # **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [43]:
twoD_array = np.random.randint(0, 2, size=(3, 3))
twoD_array

array([[1, 1, 0],
       [0, 1, 0],
       [0, 1, 0]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [45]:
twoD_array + np.array([1,2,3])

array([[2, 3, 3],
       [1, 3, 3],
       [1, 3, 3]])

# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [49]:
first=np.random.randint(0, 10, size=(3, 3))
first

array([[5, 2, 2],
       [8, 9, 7],
       [5, 3, 8]])

In [50]:
second=np.random.randint(0, 10, size=(3, 3))
second

array([[4, 2, 5],
       [3, 2, 6],
       [2, 8, 9]])

In [51]:
horizontal=np.concatenate((first,second),axis=1)#along row
print(horizontal)

[[5 2 2 4 2 5]
 [8 9 7 3 2 6]
 [5 3 8 2 8 9]]


In [52]:
vertical=np.concatenate((first,second),axis=0)#along col
print(vertical)

[[5 2 2]
 [8 9 7]
 [5 3 8]
 [4 2 5]
 [3 2 6]
 [2 8 9]]


In [58]:
horizontal_split=np.hsplit(horizontal,2)
horizontal_split

[array([[5, 2, 2],
        [8, 9, 7],
        [5, 3, 8]]),
 array([[4, 2, 5],
        [3, 2, 6],
        [2, 8, 9]])]

In [60]:
vertical_split=np.vsplit(vertical,2)#(array.quantityof equal array if 3 the output will be three array)
vertical_split

[array([[5, 2, 2],
        [8, 9, 7],
        [5, 3, 8]]),
 array([[4, 2, 5],
        [3, 2, 6],
        [2, 8, 9]])]

## **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [86]:
#method 01
list_4=[1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]
count=0
counting=[]
for i in list_4:
    for j in list_4:
        if i==j:
            count+=1
    counting_value.append(i)
    counting.append(count)
    count=0
max_value=max(counting)
index_of_highest_value=counting.index(max_value)
number_against_index_value=list_4[index_of_highest_value]
mode=number_against_index_value
mode

1

In [89]:
#method 02
list_4=[1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]
counting=[]
for i in list_4:
    element_count=list_4.count(i)
    counting.append(element_count)
max_value=max(counting)
index_of_highest_value=counting.index(max_value)
number_against_index_value=list_4[index_of_highest_value]
mode=number_against_index_value
mode

1

# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

